name: .NET Core

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
    - dev
    - feature/*
    - hotfix/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore ./App.Storage/App.Storage.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore ./App.Storage/App.Storage.sln
    - name: Test
      run: dotnet test --no-restore --verbosity normal ./App.Storage/App.Storage.sln
